### PR TITLE
Build from a directory

### PR DESCRIPTION
**Pull request by richfitz**
This introduces a new public function `nomad::build_path` for building without cloning the upstream target repo.

### CODE REVIEW

**Comment by zkamvar** [comment]
I should be able to get to this in about an hour or so. Internet went out at my flat and I have a doctor’s appointment any time now.

**Comment by zkamvar** [comment]
@richfitz, do you need anything more to merge this?

**Comment by richfitz** [comment]
Um, no. I just assumed you'd merge it as reviewer

**Comment by zkamvar** [comment]
Aha! I was assuming you would merge it as maintainer.

**Pull request merged**
